-- ============================================================================
-- RELATIONSHIP OS - V2 Custom Evaluations Migration
-- ============================================================================

-- 1. Custom Evaluations Table
-- Stores metadata about an AI-generated evaluation for a specific couple
CREATE TABLE IF NOT EXISTS custom_evaluations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    couple_id UUID NOT NULL REFERENCES couples(id) ON DELETE CASCADE,
    created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('draft', 'active', 'completed', 'archived')),
    gemini_prompt_version TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Custom Evaluation Questions Table
-- Stores the dynamic questions generated by Gemini for an evaluation
CREATE TABLE IF NOT EXISTS custom_evaluation_questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evaluation_id UUID NOT NULL REFERENCES custom_evaluations(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    question_type TEXT NOT NULL CHECK (question_type IN ('LIKERT-5', 'LIKERT-7', 'OPEN', 'BOOLEAN')),
    response_scale JSONB, -- Defines labels for scales if not purely open
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Custom Evaluation Answers Table
-- Stores user responses to the custom questions
CREATE TABLE IF NOT EXISTS custom_evaluation_answers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evaluation_id UUID NOT NULL REFERENCES custom_evaluations(id) ON DELETE CASCADE,
    question_id UUID NOT NULL REFERENCES custom_evaluation_questions(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    answer_value JSONB NOT NULL,
    answered_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, question_id)
);

-- 4. Custom Evaluation Insights Table
-- Stores the final AI coaching once both partners complete
CREATE TABLE IF NOT EXISTS custom_evaluation_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evaluation_id UUID NOT NULL REFERENCES custom_evaluations(id) ON DELETE CASCADE,
    ai_summary TEXT NOT NULL,
    ai_actions JSONB,
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- RLS Policies
-- ============================================================================

ALTER TABLE custom_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_evaluation_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_evaluation_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_evaluation_insights ENABLE ROW LEVEL SECURITY;

-- custom_evaluations
CREATE POLICY "Users can view couple custom evaluations" ON custom_evaluations
    FOR SELECT USING (
        couple_id IN (SELECT couple_id FROM couple_members WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can create custom evaluations" ON custom_evaluations
    FOR INSERT WITH CHECK (
        couple_id IN (SELECT couple_id FROM couple_members WHERE user_id = auth.uid()) AND
        created_by = auth.uid()
    );

CREATE POLICY "Users can update their custom evaluations" ON custom_evaluations
    FOR UPDATE USING (
        couple_id IN (SELECT couple_id FROM couple_members WHERE user_id = auth.uid())
    );

-- custom_evaluation_questions (read-only for users, created alongside evaluation by a system/admin context or serverless fn)
CREATE POLICY "Users can view couple custom evaluation questions" ON custom_evaluation_questions
    FOR SELECT USING (
        evaluation_id IN (
            SELECT id FROM custom_evaluations WHERE couple_id IN (
                SELECT couple_id FROM couple_members WHERE user_id = auth.uid()
            )
        )
    );

-- Users can theoretically inserts since Server Actions run with user context
CREATE POLICY "Users can insert couple custom evaluation questions" ON custom_evaluation_questions
    FOR INSERT WITH CHECK (
        evaluation_id IN (
            SELECT id FROM custom_evaluations WHERE couple_id IN (
                SELECT couple_id FROM couple_members WHERE user_id = auth.uid()
            )
        )
    );

-- custom_evaluation_answers
CREATE POLICY "Users can view couple answers" ON custom_evaluation_answers
    FOR SELECT USING (
        evaluation_id IN (
            SELECT id FROM custom_evaluations WHERE couple_id IN (
                SELECT couple_id FROM couple_members WHERE user_id = auth.uid()
            )
        )
    );

CREATE POLICY "Users can insert own answers" ON custom_evaluation_answers
    FOR INSERT WITH CHECK (
        user_id = auth.uid() AND
        evaluation_id IN (
            SELECT id FROM custom_evaluations WHERE couple_id IN (
                SELECT couple_id FROM couple_members WHERE user_id = auth.uid()
            )
        )
    );

CREATE POLICY "Users can update own answers" ON custom_evaluation_answers
    FOR UPDATE USING (user_id = auth.uid());

-- custom_evaluation_insights
CREATE POLICY "Users can view couple custom evaluation insights" ON custom_evaluation_insights
    FOR SELECT USING (
        evaluation_id IN (
            SELECT id FROM custom_evaluations WHERE couple_id IN (
                SELECT couple_id FROM couple_members WHERE user_id = auth.uid()
            )
        )
    );

CREATE POLICY "Users can insert couple custom evaluation insights" ON custom_evaluation_insights
    FOR INSERT WITH CHECK (
        evaluation_id IN (
            SELECT id FROM custom_evaluations WHERE couple_id IN (
                SELECT couple_id FROM couple_members WHERE user_id = auth.uid()
            )
        )
    );

-- Add update trigger
CREATE TRIGGER update_custom_evaluations_modtime
BEFORE UPDATE ON custom_evaluations
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
